import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {useMemo,useState,type FormEvent} from 'react';
import {api} from '../api';

type Period={id:number;startDate:string;endDate:string;type:'held'|'confirmed'|'owner_block'|'maintenance'|'private_use';reason?:string};
type RentalSettings={minimumStayMonths:number;maximumStayMonths?:number;minimumNoticeDays:number;viewingNoticeHours:number;viewingWindowStart:string;viewingWindowEnd:string;costEstimate:{rent:number;utilities:number;meals:number;transport:number;total:number};cancellationPolicy?:string};
type CalendarData={snapshot:{status:string;label:string;nextAvailableFrom?:string};busyPeriods:Period[];settings:RentalSettings};
const iso=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const money=(value:number)=>`Rs. ${value.toLocaleString('en-LK')}`;

export function AvailabilityCalendar({listingId,ownerMode=false}:{listingId:number;ownerMode?:boolean}){
  const qc=useQueryClient();const now=new Date();const[month,setMonth]=useState(new Date(now.getFullYear(),now.getMonth(),1));const[notice,setNotice]=useState('');
  const{data}=useQuery({queryKey:['availability',listingId],queryFn:async()=>(await api.get(`/listings/${listingId}/availability`)).data as CalendarData,enabled:!!listingId});
  const days=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1);const last=new Date(month.getFullYear(),month.getMonth()+1,0);const rows:Array<Date|null>=Array(first.getDay()).fill(null);for(let day=1;day<=last.getDate();day++)rows.push(new Date(month.getFullYear(),month.getMonth(),day));while(rows.length%7)rows.push(null);return rows},[month]);
  const periodFor=(date:Date)=>data?.busyPeriods.find(item=>iso(date)>=item.startDate&&iso(date)<=item.endDate);
  const block=useMutation({mutationFn:(body:unknown)=>api.post(`/owner/listings/${listingId}/availability-blocks`,body),onSuccess:async()=>{setNotice('Unavailable dates saved.');await qc.invalidateQueries({queryKey:['availability',listingId]})}});
  const settings=useMutation({mutationFn:(body:unknown)=>api.put(`/owner/listings/${listingId}/rental-settings`,body),onSuccess:async()=>{setNotice('Rental and viewing rules saved.');await qc.invalidateQueries({queryKey:['availability',listingId]})}});
  const remove=useMutation({mutationFn:(id:number)=>api.delete(`/owner/availability-blocks/${id}`),onSuccess:()=>qc.invalidateQueries({queryKey:['availability',listingId]})});
  const saveBlock=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const fields=new FormData(event.currentTarget);block.mutate({startDate:fields.get('startDate'),endDate:fields.get('endDate'),type:fields.get('type'),reason:fields.get('reason')})};
  const saveSettings=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);settings.mutate({minimumStayMonths:Number(f.get('minimumStayMonths')),maximumStayMonths:Number(f.get('maximumStayMonths'))||null,minimumNoticeDays:Number(f.get('minimumNoticeDays')),viewingNoticeHours:Number(f.get('viewingNoticeHours')),viewingWindowStart:f.get('viewingWindowStart'),viewingWindowEnd:f.get('viewingWindowEnd'),utilitiesEstimateLkr:Number(f.get('utilitiesEstimateLkr')),mealsEstimateLkr:Number(f.get('mealsEstimateLkr')),transportEstimateLkr:Number(f.get('transportEstimateLkr')),cancellationPolicy:f.get('cancellationPolicy')})};
  if(!data)return <div className="skeleton"/>;
  return <section className="availability-calendar" aria-label="Property availability calendar"><header><div><span>Live availability</span><h2>Know which dates are genuinely open</h2><p>{data.snapshot.label}. Viewing requests do not block dates.</p></div><div className="calendar-month-nav"><button aria-label="Previous month" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><i className="bi bi-chevron-left"/></button><strong>{month.toLocaleDateString('en-LK',{month:'long',year:'numeric'})}</strong><button aria-label="Next month" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><i className="bi bi-chevron-right"/></button></div></header>
    <div className="calendar-weekdays">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=><b key={day}>{day}</b>)}</div><div className="calendar-days">{days.map((date,index)=>{const period=date?periodFor(date):undefined;const past=date?iso(date)<iso(now):false;return <div key={date?.toISOString()||`blank-${index}`} className={`${!date?'is-blank ':''}${period?`is-${period.type} `:''}${past?'is-past':''}`} title={period?`${period.type.replaceAll('_',' ')}: ${period.startDate} to ${period.endDate}`:'Available'}>{date&&<><span>{date.getDate()}</span>{period&&<i/>}</>}</div>})}</div>
    <div className="calendar-legend"><span><i className="is-open"/>Available</span><span><i className="is-held"/>48-hour hold</span><span><i className="is-confirmed"/>Reserved</span><span><i className="is-blocked"/>Owner unavailable</span></div>
    <div className="monthly-cost"><div><small>Rent</small><strong>{money(data.settings.costEstimate.rent)}</strong></div><i>+</i><div><small>Utilities estimate</small><strong>{money(data.settings.costEstimate.utilities)}</strong></div><i>+</i><div><small>Meals estimate</small><strong>{money(data.settings.costEstimate.meals)}</strong></div><i>+</i><div><small>Transport estimate</small><strong>{money(data.settings.costEstimate.transport)}</strong></div><div className="is-total"><small>Estimated monthly total</small><strong>{money(data.settings.costEstimate.total)}</strong></div></div>
    {ownerMode&&<><form className="rental-settings-form" onSubmit={saveSettings}><div><strong>Rental and viewing rules</strong><small>These rules are enforced by the API for every request.</small></div><label>Minimum stay (months)<input type="number" name="minimumStayMonths" min="1" max="24" defaultValue={data.settings.minimumStayMonths} required/></label><label>Maximum stay (months)<input type="number" name="maximumStayMonths" min="1" max="60" defaultValue={data.settings.maximumStayMonths||''}/></label><label>Move-in notice (days)<input type="number" name="minimumNoticeDays" min="0" max="90" defaultValue={data.settings.minimumNoticeDays} required/></label><label>Viewing notice (hours)<input type="number" name="viewingNoticeHours" min="1" max="168" defaultValue={data.settings.viewingNoticeHours} required/></label><label>Viewings from<input type="time" name="viewingWindowStart" defaultValue={data.settings.viewingWindowStart} required/></label><label>Viewings until<input type="time" name="viewingWindowEnd" defaultValue={data.settings.viewingWindowEnd} required/></label><label>Utilities estimate<input type="number" name="utilitiesEstimateLkr" min="0" defaultValue={data.settings.costEstimate.utilities} required/></label><label>Meals estimate<input type="number" name="mealsEstimateLkr" min="0" defaultValue={data.settings.costEstimate.meals} required/></label><label>Transport estimate<input type="number" name="transportEstimateLkr" min="0" defaultValue={data.settings.costEstimate.transport} required/></label><label className="is-wide">Cancellation policy<textarea name="cancellationPolicy" maxLength={1000} defaultValue={data.settings.cancellationPolicy||''}/></label><button disabled={settings.isPending}>Save rules</button></form><form className="calendar-owner-form" onSubmit={saveBlock}><strong>Block unavailable dates</strong><label>From<input type="date" name="startDate" min={iso(now)} required/></label><label>To<input type="date" name="endDate" min={iso(now)} required/></label><label>Reason type<select name="type"><option value="owner_block">Unavailable</option><option value="maintenance">Maintenance</option><option value="private_use">Private use</option></select></label><label>Private note<input name="reason" maxLength={300}/></label><button disabled={block.isPending}>Block dates</button></form>{notice&&<div className="notice notice-info">{notice}</div>}<div className="calendar-block-list">{data.busyPeriods.filter(item=>['owner_block','maintenance','private_use'].includes(item.type)).map(item=><span key={`${item.type}-${item.id}`}>{item.startDate} – {item.endDate} · {item.type.replaceAll('_',' ')} <button aria-label="Remove availability block" onClick={()=>remove.mutate(item.id)}><i className="bi bi-x"/></button></span>)}</div></>}
    <small className="calendar-disclaimer">Cost values are owner estimates or disclosed defaults, not guaranteed bills. Confirm actual utilities, meals and travel costs before reserving.</small>
  </section>
}
