import { BuddyMark } from './Shell';

export type PriceInsight={available:boolean;label:string;confidence:string;peerCount:number;listingPriceLkr?:number;peerMedianLkr?:number;peerRangeLkr?:{low:number;high:number};priceVsMedianPercent?:number;marketPercentile?:number;facilitySignals?:Array<{facility:string;observedDifferenceLkr:number}>;disclaimer?:string};
const money=(value:number)=>`Rs. ${value.toLocaleString('en-LK')}`;
export function PriceIntelligence({insight}:{insight:PriceInsight}){
  if(!insight.available)return <section className="price-intelligence is-empty"><i className="bi bi-bar-chart"/><div><span>Buddy price check</span><h2>More comparable listings are needed.</h2><p>Buddy will show a market range after enough similar published places exist.</p></div></section>;
  const delta=insight.priceVsMedianPercent||0;
  return <section className="price-intelligence"><header><div><span><BuddyMark className="is-symbol"/> Buddy price intelligence</span><h2>{insight.label}</h2><p>Compared with {insight.peerCount} published peer listings in the same district.</p></div><b className={delta>10?'is-high':delta<-10?'is-low':'is-fair'}>{delta>0?'+':''}{delta}%<small>vs median</small></b></header><div className="price-range"><span><small>Typical middle range</small><strong>{money(insight.peerRangeLkr!.low)} – {money(insight.peerRangeLkr!.high)}</strong></span><span><small>Peer median</small><strong>{money(insight.peerMedianLkr!)}</strong></span><span><small>Evidence confidence</small><strong>{insight.confidence}</strong></span></div>{Boolean(insight.facilitySignals?.length)&&<div className="price-facility-signals">{insight.facilitySignals!.map(signal=><span key={signal.facility}><i className="bi bi-check2-circle"/>{signal.facility}<b>{signal.observedDifferenceLkr===0?'neutral':`${signal.observedDifferenceLkr>0?'+':''}${money(signal.observedDifferenceLkr)}`}</b></span>)}</div>}<small className="price-disclaimer"><i className="bi bi-info-circle"/>{insight.disclaimer}</small></section>;
}
