import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {useState,type FormEvent} from 'react';
import {api} from '../api';
import {RoleLayout} from '../components/Shell';

type Dispute={id:number;category:string;details:string;status:string;resolution?:string;created_at:string;reporter:{name:string;role:string};reservation:{listing:{title:string}}};
type Evidence={id:number;type:string;reference:string;status:string;review_note?:string;created_at:string;user:{name:string;email:string;role:string}};
type Page<T>={data:T[];total:number};

export default function AdminTrust(){
  const qc=useQueryClient();const[active,setActive]=useState<'disputes'|'verification'>('disputes');const[message,setMessage]=useState('');
  const disputes=useQuery({queryKey:['admin','rental-disputes'],queryFn:async()=>(await api.get('/admin/rental-disputes')).data.data as Page<Dispute>});
  const evidence=useQuery({queryKey:['admin','verification-evidence'],queryFn:async()=>(await api.get('/admin/verification-evidence')).data.data as Page<Evidence>});
  const resolve=useMutation({mutationFn:({id,body}:{id:number;body:unknown})=>api.put(`/admin/rental-disputes/${id}`,body),onSuccess:async()=>{setMessage('Dispute decision saved.');await qc.invalidateQueries({queryKey:['admin','rental-disputes']})}});
  const review=useMutation({mutationFn:({id,body}:{id:number;body:unknown})=>api.put(`/admin/verification-evidence/${id}`,body),onSuccess:async()=>{setMessage('Verification decision saved.');await qc.invalidateQueries({queryKey:['admin','verification-evidence']})}});
  const resolveDispute=(id:number,event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);resolve.mutate({id,body:{status:f.get('status'),resolution:f.get('resolution')}})};
  const reviewEvidence=(id:number,event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);review.mutate({id,body:{status:f.get('status'),reviewNote:f.get('reviewNote')}})};
  return <RoleLayout role="admin"><div className="client-page-head"><div><span className="client-kicker">Human decision required</span><h1>Trust centre</h1><p>Review rental disputes and verification references with a clear, auditable human decision.</p></div><div className="trust-counts"><span>{disputes.data?.total||0}<small>disputes</small></span><span>{evidence.data?.total||0}<small>evidence items</small></span></div></div>{message&&<div className="notice notice-info">{message}</div>}<div className="trust-tabs" role="tablist"><button className={active==='disputes'?'active':''} onClick={()=>setActive('disputes')}><i className="bi bi-flag"/> Rental disputes</button><button className={active==='verification'?'active':''} onClick={()=>setActive('verification')}><i className="bi bi-patch-check"/> Verification evidence</button></div>
  {active==='disputes'?<section className="trust-queue">{(disputes.data?.data||[]).map(item=><article key={item.id}><header><div><span>{item.category.replaceAll('_',' ')}</span><h2>{item.reservation.listing.title}</h2><small>Reported by {item.reporter.name} ({item.reporter.role}) · {new Date(item.created_at).toLocaleDateString('en-LK')}</small></div><b className={`status status-${item.status}`}>{item.status}</b></header><p>{item.details}</p>{item.resolution&&<div className="trust-resolution"><strong>Decision record</strong>{item.resolution}</div>}{!['resolved','dismissed'].includes(item.status)&&<form onSubmit={event=>resolveDispute(item.id,event)}><label>Decision<select name="status" defaultValue={item.status==='open'?'investigating':item.status}><option value="investigating">Investigating</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select></label><label>Resolution<textarea name="resolution" required minLength={10} maxLength={3000} placeholder="Record evidence checked, action taken and follow-up needed."/></label><button disabled={resolve.isPending}>Save decision</button></form>}</article>)}{!disputes.data?.data.length&&<div className="empty"><h3>No rental disputes</h3><p>New tenant or owner reports will appear here.</p></div>}</section>:<section className="trust-queue">{(evidence.data?.data||[]).map(item=><article key={item.id}><header><div><span>{item.type.replaceAll('_',' ')}</span><h2>{item.user.name}</h2><small>{item.user.email} · {item.user.role} · Submitted {new Date(item.created_at).toLocaleDateString('en-LK')}</small></div><b className={`status status-${item.status}`}>{item.status}</b></header><div className="evidence-reference"><i className="bi bi-shield-lock"/><div><small>Safe reference supplied</small><strong>{item.reference}</strong></div></div>{item.review_note&&<div className="trust-resolution"><strong>Reviewer note</strong>{item.review_note}</div>}{item.status==='pending'&&<form onSubmit={event=>reviewEvidence(item.id,event)}><label>Decision<select name="status"><option value="verified">Verify</option><option value="rejected">Reject</option></select></label><label>Reviewer note<textarea name="reviewNote" required minLength={5} maxLength={500} placeholder="Describe what was checked without copying sensitive identity details."/></label><button disabled={review.isPending}>Save verification</button></form>}</article>)}{!evidence.data?.data.length&&<div className="empty"><h3>No pending verification evidence</h3><p>References submitted from the user Trust Centre will appear here.</p></div>}</section>}
  </RoleLayout>;
}
