import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {FormEvent,useState} from 'react';
import {api} from '../api';
import {RoleLayout} from '../components/Shell';
import type {Listing} from '../types';

export function AdminDashboard(){const{data}=useQuery({queryKey:['admin-dashboard'],queryFn:async()=>(await api.get('/admin/dashboard')).data});const m=data?.metrics||{};return <RoleLayout role="admin"><div className="dash-head"><div><span className="eyebrow">Platform operations</span><h1>Administrator overview</h1></div></div><div className="metrics">{[['Users',m.users],['Published',m.published],['Pending',m.pending],['Flagged reviews',m.flaggedReviews],['Conversations',m.conversations],['Searches',m.searches]].map(([label,value])=><div className="metric" key={label}><span>{label}</span><strong>{String(value??0)}</strong></div>)}</div><div className="dash-grid"><div className="panel"><div className="panel-head"><h2>Recent search activity</h2></div>{(data?.recentSearches||[]).map((x:{id:number;sanitized_query:string;result_count:number;mode:string})=><div className="list-row" key={x.id}><span className="notif-icon">⌕</span><div className="list-copy"><strong>{x.sanitized_query||'Structured filter search'}</strong><span>{x.result_count} results • {x.mode}</span></div></div>)}</div><div className={`notice ${data?.ai?.online?'notice-info':'notice-warning'}`}><strong>AI service</strong>&nbsp;{data?.ai?.online?'ready':'offline — SQL/keyword fallback active'}</div></div></RoleLayout>}

export function AdminListings(){const qc=useQueryClient();const[rejecting,setRejecting]=useState<Listing|null>(null);const{data}=useQuery({queryKey:['admin-listings'],queryFn:async()=>(await api.get('/admin/listings?perPage=50')).data});const moderate=useMutation({mutationFn:({id,action,reason}:{id:number;action:string;reason:string})=>api.post(`/admin/listings/${id}/${action}`,{reason}),onSuccess:()=>{setRejecting(null);void qc.invalidateQueries({queryKey:['admin-listings']})}});const items:Listing[]=data?.data||[];const reject=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(rejecting)moderate.mutate({id:rejecting.id,action:'reject',reason:String(new FormData(e.currentTarget).get('reason'))})};return <RoleLayout role="admin"><div className="dash-head"><div><span className="eyebrow">Moderation</span><h1>Listing approval queue</h1></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Listing</th><th>Owner</th><th>Status</th><th>Decision</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.title}</strong><br/><small>{x.area} • Rs. {x.price.toLocaleString('en-LK')}</small></td><td>{x.ownerName}</td><td><span className={`status status-${x.status}`}>{x.status}</span></td><td><div className="table-actions">{x.status==='pending_review'&&<><button className="btn btn-primary btn-sm" onClick={()=>moderate.mutate({id:x.id,action:'approve',reason:'Details, images, location and owner record verified by administrator.'})}>Approve</button><button className="btn btn-danger btn-sm" onClick={()=>setRejecting(x)}>Reject</button></>}{x.status==='published'&&<button className="btn btn-danger btn-sm" onClick={()=>moderate.mutate({id:x.id,action:'suspend',reason:'Suspended after administrator moderation review.'})}>Suspend</button>}{x.status==='suspended'&&<button className="btn btn-primary btn-sm" onClick={()=>moderate.mutate({id:x.id,action:'restore',reason:'Restored after corrective review.'})}>Restore</button>}</div></td></tr>)}</tbody></table></div>{rejecting&&<div className="modal-backdrop"><form className="modal" onSubmit={reject}><h2>Reject {rejecting.title}</h2><p>Give the owner specific, actionable changes needed for resubmission.</p><textarea className="textarea" name="reason" required minLength={8} maxLength={1000}/><div className="modal-actions"><button type="button" className="btn btn-ghost" onClick={()=>setRejecting(null)}>Cancel</button><button className="btn btn-danger">Reject with feedback</button></div></form></div>}</RoleLayout>}

type OwnerRow={id:number;verification_status:string;business_name?:string;user:{id:number;name:string;email:string}};
export function AdminOwners(){const qc=useQueryClient();const{data}=useQuery({queryKey:['admin','owners'],queryFn:async()=>(await api.get('/admin/owners')).data});const act=useMutation({mutationFn:({id,decision}:{id:number;decision:string})=>api.post(`/admin/owners/${id}/verify`,{decision,reason:`Owner ${decision} after identity-reference and contact checks.`}),onSuccess:()=>qc.invalidateQueries({queryKey:['admin','owners']})});const items:OwnerRow[]=data?.data||[];return <RoleLayout role="admin"><div className="dash-head"><div><span className="eyebrow">Trust & safety</span><h1>Owner verification queue</h1></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Owner</th><th>Business</th><th>Status</th><th>Decision</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.user.name}</strong><br/><small>{x.user.email}</small></td><td>{x.business_name||'Individual owner'}</td><td><span className="status status-pending_review">{x.verification_status}</span></td><td><div className="table-actions"><button className="btn btn-primary btn-sm" onClick={()=>act.mutate({id:x.id,decision:'verified'})}>Verify</button><button className="btn btn-danger btn-sm" onClick={()=>act.mutate({id:x.id,decision:'rejected'})}>Reject</button></div></td></tr>)}</tbody></table></div>{!items.length&&<div className="empty"><h3>No owners awaiting verification</h3></div>}</RoleLayout>}

type UserRow={id:number;name:string;email:string;role:string;status:string};
export function AdminUsers(){const qc=useQueryClient();const[q,setQ]=useState('');const{data}=useQuery({queryKey:['admin','users',q],queryFn:async()=>(await api.get('/admin/users',{params:{q}})).data});const act=useMutation({mutationFn:({id,status}:{id:number;status:string})=>api.post(`/admin/users/${id}/status`,{status,reason:`Account ${status} after administrator account review.`}),onSuccess:()=>qc.invalidateQueries({queryKey:['admin','users']})});const items:UserRow[]=data?.data||[];return <RoleLayout role="admin"><div className="dash-head"><div><span className="eyebrow">Access administration</span><h1>Users</h1></div><label className="field">Search users<input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Name or email"/></label></div><div className="table-wrap"><table className="table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.name}</strong><br/><small>{x.email}</small></td><td>{x.role}</td><td><span className={`status status-${x.status}`}>{x.status}</span></td><td>{x.role!=='admin'&&<div className="table-actions">{x.status==='active'?<button className="btn btn-danger btn-sm" onClick={()=>act.mutate({id:x.id,status:'suspended'})}>Suspend</button>:<button className="btn btn-primary btn-sm" onClick={()=>act.mutate({id:x.id,status:'active'})}>Restore</button>}</div>}</td></tr>)}</tbody></table></div></RoleLayout>}

type AdminReview={id:number;rating:number;body:string;moderation_status:string;tenant:{name:string};listing:{title:string}};
export function AdminReviews(){const qc=useQueryClient();const{data}=useQuery({queryKey:['admin','reviews'],queryFn:async()=>(await api.get('/admin/reviews')).data});const act=useMutation({mutationFn:({id,action}:{id:number;action:string})=>api.post(`/admin/reviews/${id}/${action}`,{reason:`Review ${action} after content-policy assessment.`}),onSuccess:()=>qc.invalidateQueries({queryKey:['admin','reviews']})});const items:AdminReview[]=data?.data||[];return <RoleLayout role="admin"><div className="dash-head"><div><span className="eyebrow">Content moderation</span><h1>Reviews & reports</h1></div></div><div className="panel">{items.map(r=><article className="review" key={r.id}><div className="review-head"><strong>{r.tenant.name} • {r.listing.title}</strong><span className="stars">{'★'.repeat(r.rating)}</span></div><p>{r.body}</p><div className="table-actions"><span className={`status status-${r.moderation_status}`}>{r.moderation_status}</span>{r.moderation_status==='hidden'?<button className="btn btn-primary btn-sm" onClick={()=>act.mutate({id:r.id,action:'restore'})}>Restore</button>:<button className="btn btn-danger btn-sm" onClick={()=>act.mutate({id:r.id,action:'hide'})}>Hide</button>}</div></article>)}</div></RoleLayout>}

type Audit={id:number;action:string;target_type:string;target_id:number;reason:string;created_at:string};
export function AdminAudit(){const{data}=useQuery({queryKey:['admin','audit'],queryFn:async()=>(await api.get('/admin/audit-logs')).data});const items:Audit[]=data?.data||[];return <RoleLayout role="admin"><div className="dash-head"><div><span className="eyebrow">Immutable history</span><h1>Administrative audit log</h1></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Action</th><th>Target</th><th>Reason</th><th>Time</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.action}</strong></td><td>{x.target_type} #{x.target_id}</td><td>{x.reason}</td><td>{new Date(x.created_at).toLocaleString('en-LK',{timeZone:'Asia/Colombo'})}</td></tr>)}</tbody></table></div></RoleLayout>}

export function AdminNotifications(){const[result,setResult]=useState('');const send=useMutation({mutationFn:(body:unknown)=>api.post('/admin/notifications',body),onSuccess:r=>setResult(`${r.data.recipients} notifications queued.`)});const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);send.mutate({target:f.get('target'),title:f.get('title'),message:f.get('message'),link:f.get('link')||null,userIds:[]})};return <RoleLayout role="admin"><div className="dash-head"><div><span className="eyebrow">Platform communication</span><h1>Notification composer</h1></div></div><form className="form-card" onSubmit={submit}>{result&&<div className="notice notice-info">{result}</div>}<div className="form"><label className="field">Recipients<select className="select" name="target"><option value="all">All active users</option><option value="tenant">All tenants</option><option value="owner">All owners</option></select></label><label className="field">Title<input className="input" name="title" required maxLength={160}/></label><label className="field">Message<textarea className="textarea" name="message" required maxLength={600}/></label><label className="field">Safe internal link (optional)<input className="input" name="link" pattern="/[A-Za-z0-9_\-/]*" placeholder="/search"/></label></div><div className="actions-row"><button className="btn btn-primary">Send notification</button></div></form></RoleLayout>}

export function AdminAi() {
  const { data } = useQuery({ queryKey: ['admin-dashboard'], queryFn: async () => (await api.get('/admin/dashboard')).data, refetchInterval: 30000 });
  const ai = data?.ai || {};
  return <RoleLayout role="admin"><div className="dash-head"><div><span className="eyebrow">Internal intelligence service</span><h1>AI health, index & dataset</h1></div></div><div className="metrics"><div className="metric"><span>Service</span><strong>{ai.online ? 'Online' : 'Offline'}</strong></div><div className="metric"><span>Models ready</span><strong>{ai.modelReady ? 'Yes' : 'No'}</strong></div><div className="metric"><span>FAISS index</span><strong>{ai.indexReady ? 'Ready' : 'Fallback'}</strong></div><div className="metric"><span>Index size</span><strong>{String(ai.indexSize ?? 0)}</strong></div></div><div className={`notice ${ai.online ? 'notice-info' : 'notice-warning'}`}>{ai.online ? 'The PHP API is connected to the authenticated Flask service.' : 'The application remains usable through structured filters and keyword search. Failed analysis/index jobs can be retried from the queue.'}</div><div className="panel dataset-panel"><div className="panel-head"><div><span className="eyebrow">Submitted data status</span><h2>Transparent academic dataset</h2></div></div><div className="metrics"><div className="metric"><span>Live retrieval corpus</span><strong>{String(data?.metrics?.published ?? 24)}</strong><small>Synthetic seeded listings</small></div><div className="metric"><span>Search evaluation</span><strong>3</strong><small>CC0 synthetic query pairs</small></div><div className="metric"><span>Review evaluation</span><strong>5</strong><small>CC0 synthetic labelled reviews</small></div></div><p className="muted">The chatbot ranks the current published database corpus. The small checked-in fixtures validate the training and evaluation pipeline only; no Kaggle dataset is claimed.</p></div></RoleLayout>;
}
