import {useQuery} from '@tanstack/react-query';
import {FormEvent,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api';
import {RoleLayout} from '../components/Shell';

type Results={users:Array<{id:number;name:string;email:string;role:string;status:string}>;listings:Array<{id:number;title:string;public_slug:string;city:string;status:string}>;reviews:Array<{id:number;body:string;rating:number;moderation_status:string;tenant:{name:string};listing:{title:string}}> ;conversations:Array<{id:number;subject:string;updated_at:string;listing:{title:string};tenant:{name:string};owner:{name:string}}>};
export function AdminSearch(){const[input,setInput]=useState('');const[q,setQ]=useState('');const{data,isFetching}=useQuery({queryKey:['admin-global-search',q],enabled:q.length>=2,queryFn:async()=>(await api.get('/admin/search',{params:{q}})).data as Results});const submit=(e:FormEvent)=>{e.preventDefault();setQ(input.trim())};return <RoleLayout role="admin"><div className="dash-head"><div><span className="eyebrow">Platform-wide lookup</span><h1>Global search</h1><p>Conversation subjects and participants are searchable; private message bodies are excluded.</p></div></div><form className="hero-search admin-search" onSubmit={submit}><span className="search-icon">⌕</span><label className="sr-only" htmlFor="admin-query">Search users, listings, reviews and conversation metadata</label><input id="admin-query" value={input} onChange={e=>setInput(e.target.value)} minLength={2} maxLength={100} required placeholder="Name, email, listing reference, review text…"/><button className="btn btn-primary">Search</button></form>{isFetching&&<div className="skeleton"/>}{data&&<div className="admin-search-grid"><ResultPanel title="Users" rows={data.users.map(x=><div className="list-row" key={x.id}><span className="notif-icon">♙</span><div className="list-copy"><strong>{x.name}</strong><span>{x.email} • {x.role} • {x.status}</span></div></div>)}/><ResultPanel title="Listings" rows={data.listings.map(x=><div className="list-row" key={x.id}><span className="notif-icon">⌂</span><div className="list-copy"><Link to={`/listing/${x.id}`}><strong>{x.title}</strong></Link><span>{x.public_slug} • {x.city} • {x.status}</span></div></div>)}/><ResultPanel title="Reviews" rows={data.reviews.map(x=><div className="list-row" key={x.id}><span className="notif-icon">★</span><div className="list-copy"><strong>{x.tenant?.name} • {x.listing?.title}</strong><span>{x.body} • {x.moderation_status}</span></div></div>)}/><ResultPanel title="Conversation metadata" rows={data.conversations.map(x=><div className="list-row" key={x.id}><span className="notif-icon">✉</span><div className="list-copy"><strong>{x.subject}</strong><span>{x.listing?.title} • {x.tenant?.name} ↔ {x.owner?.name}</span></div></div>)}/></div>}</RoleLayout>}
function ResultPanel({title,rows}:{title:string;rows:React.ReactNode[]}){return <section className="panel"><div className="panel-head"><h2>{title}</h2><span>{rows.length}</span></div>{rows.length?rows:<div className="empty"><p>No matches</p></div>}</section>}
