import { useQuery } from '@tanstack/react-query';
import { type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../api';
import { ListingCard } from '../components/ListingCard';
import { PublicLayout } from '../components/Shell';
import type { Destination, Listing } from '../types';

export default function Home() {
  const { data: featured = [] } = useQuery({ queryKey: ['featured'], queryFn: async () => (await api.get('/listings/featured')).data.data as Listing[] });
  const { data: destinations = [] } = useQuery({ queryKey: ['destinations'], queryFn: async () => (await api.get('/destinations')).data.data as Destination[] });
  const popularNames = ['University of Moratuwa', 'University of Colombo', 'SLIIT Malabe Campus', 'NSBM Green University', 'ICBT Campus - Colombo', 'ICBT Campus - Kandy', 'World Trade Center Colombo', 'Kandy City Centre'];
  const popularDestinations = popularNames.map(name => destinations.find(place => place.name === name)).filter((place): place is Destination => Boolean(place));
  const openAssistant = (message?: string) => window.dispatchEvent(new CustomEvent('smartbodim:open-assistant', { detail: { message } }));
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); openAssistant(String(new FormData(event.currentTarget).get('q') || '')); };
  return <PublicLayout>
    <section className="sb-hero"><div className="container"><div className="row align-items-center g-5"><div className="col-lg-6"><span className="sb-kicker"><i className="bi bi-stars" /> AI-powered Sri Lankan stay finder</span><h1>Live closer.<br /><em>Spend less time commuting.</em></h1><p className="sb-lead">Tell Bodim AI where you study or work. It ranks verified rooms by fit, calculates distance, and shows the nearest transport, supermarket, hospital and food options.</p><form className="sb-hero-search" onSubmit={submit}><i className="bi bi-chat-square-text" /><input name="q" required minLength={2} aria-label="Describe the accommodation you need" placeholder="e.g. WiFi room near University of Moratuwa under 35,000" /><button>Find with AI <i className="bi bi-arrow-right" /></button></form><div className="sb-prompt-row">{['Near SLIIT Malabe', 'Female room near UoC', 'Under Rs. 30,000'].map(prompt => <button key={prompt} onClick={() => openAssistant(prompt)}>{prompt}</button>)}</div><div className="sb-proof"><div><strong>24</strong><span>verified stays</span></div><div><strong>{destinations.length || 18}</strong><span>campus & work hubs</span></div><div><strong>5</strong><span>essential place types</span></div></div></div><div className="col-lg-6"><div className="sb-hero-visual"><img src={featured[0]?.image || 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267d?auto=format&fit=crop&w=1200&q=80'} alt="Bright verified room" /><div className="sb-visual-card sb-distance-card"><i className="bi bi-geo-alt-fill" /><div><small>Distance intelligence</small><strong>4.2 km to campus</strong></div></div><div className="sb-visual-card sb-essentials-card"><strong>Everything nearby</strong><span><i className="bi bi-bus-front" /> Bus</span><span><i className="bi bi-cart3" /> Food City</span><span><i className="bi bi-hospital" /> Hospital</span></div></div></div></div></div></section>
    <section className="sb-destination-strip"><div className="container"><div className="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-4"><div><span className="sb-kicker">Start from your daily destination</span><h2 className="mb-0">Popular campuses and workplaces</h2></div><Link className="sb-arrow-link" to="/nearby">Open full proximity finder <i className="bi bi-arrow-up-right" /></Link></div><div className="sb-destination-grid">{popularDestinations.map(place => <Link to={`/nearby?destination=${encodeURIComponent(place.name)}`} key={place.id}><span><i className={`bi ${place.type === 'campus' ? 'bi-mortarboard-fill' : 'bi-briefcase-fill'}`} /></span><div><strong>{place.name}</strong><small>{place.branchName ? `${place.branchName} branch` : place.type === 'campus' ? 'Campus' : 'Workplace'}</small></div><i className="bi bi-chevron-right" /></Link>)}</div></div></section>
    <section className="sb-section bg-white"><div className="container"><div className="sb-section-head"><div><span className="sb-kicker">Human verified, AI ranked</span><h2>Places worth looking at</h2><p>Real application records with privacy-safe public locations.</p></div><Link className="sb-arrow-link" to="/search">View all listings <i className="bi bi-arrow-right" /></Link></div><div className="row g-4">{featured.map(item => <div className="col-md-6 col-xl-4" key={item.id}><ListingCard item={item} /></div>)}</div></div></section>
    <section className="sb-section sb-how"><div className="container"><div className="row g-5 align-items-center"><div className="col-lg-5"><span className="sb-kicker">More than another listing website</span><h2>One decision view for your entire daily life.</h2><p>Price alone does not tell you whether a bodim is practical. Bodimwise brings accommodation, destination distance, everyday essentials and trust signals together.</p><Link className="btn sb-btn-primary rounded-pill px-4 py-3" to="/about">Learn how the system works</Link></div><div className="col-lg-7"><div className="sb-feature-grid">{[['bi-chat-heart','Describe your real need','Natural-language AI understands location, price and facilities.'],['bi-signpost-split','Measure the distance','Haversine calculations compare every eligible listing to your destination.'],['bi-buildings','Check daily essentials','See bus, rail, supermarket, hospital and food proximity.'],['bi-patch-check','Verify before deciding','Only published listings are recommended; exact addresses stay private.']].map(([icon,title,copy],index)=><article key={title}><span>{String(index+1).padStart(2,'0')}</span><i className={`bi ${icon}`} /><h3>{title}</h3><p>{copy}</p></article>)}</div></div></div></div></section>
  </PublicLayout>;
}
