import {PublicLayout} from '../components/Shell';

const copy={
  safety:{title:'Safety guidance',lead:'A verified listing is a moderation signal—not a guarantee. Keep control of every viewing and payment decision.',items:[['View before paying','Visit in daylight, bring someone you trust and verify the person showing the property.'],['Keep records','Use in-platform messages, ask for written terms and retain receipts for any lawful payment made directly.'],['Protect personal data','Do not send identity scans, banking passwords or one-time codes through messages.'],['Report concerns','Use the listing and review reporting tools, and contact local authorities for immediate danger.']]},
  privacy:{title:'Privacy overview',lead:'Bodimwise stores only the data needed for accounts, property workflows and platform safety.',items:[['What is stored','Account and profile details, listings, favorites, searches, messages, reviews, notifications and moderation records.'],['What stays private','Passwords are hashed, street addresses are not returned publicly and message bodies are participant-only.'],['AI boundary','Private messages, exact addresses and contact details are not embedded. The matching service receives only eligible public listing text for the requested feature.'],['Your controls','You can update your profile, delete your reviews and notifications, and archive a non-admin account.']]},
  terms:{title:'Terms of use',lead:'These terms explain the core responsibilities that keep Bodimwise useful and safe.',items:[['No payment service','The platform does not collect rent, deposits, subscriptions or listing fees.'],['User responsibility','Users must provide lawful, accurate content and independently verify properties and counterparties.'],['Moderation','Administrators may verify, reject, suspend, hide or archive content and accounts for safety and policy enforcement.'],['AI disclosure','AI ranking and summaries are assistive and may be wrong. They do not verify a property or replace human judgment.']]},
};

export function InfoPage({kind}:{kind:keyof typeof copy}){
  const page=copy[kind];
  return <PublicLayout><section className="page-hero"><div className="container"><span className="eyebrow">Bodimwise policy</span><h1>{page.title}</h1><p className="lead">{page.lead}</p></div></section><section className="section"><div className="container steps">{page.items.map(([title,body],i)=><article className="step policy-card" key={title}><span className="step-no">0{i+1}</span><h2>{title}</h2><p>{body}</p></article>)}</div></section></PublicLayout>;
}

export function AboutPage(){
  const process=[['Smart matching','Our semantic search understands meaning across budget, facilities, room types and everyday needs.'],['Eligibility filtering','Only available, administrator-published listings reach the ranker.'],['Proximity calculation','Every candidate is measured against the campus or workplace you select.'],['Neighbourhood context','Nearby transport, healthcare, supermarkets and food options are shown with distance estimates.']];
  return <PublicLayout>
    <section className="sb-page-hero sb-about-hero"><div className="container"><div className="row align-items-center g-5"><div className="col-lg-7"><span className="sb-kicker"><i className="bi bi-house-heart"/> About Bodimwise</span><h1>A smarter way to choose where your day begins.</h1><p>Bodimwise helps Sri Lankan students and workers discover trusted accommodation using natural-language search, destination distance and practical neighbourhood intelligence.</p></div><div className="col-lg-5"><div className="sb-about-stat"><strong>One clear decision</strong><span>Place · commute · essentials · trust</span></div></div></div></div></section>
    <section className="sb-section bg-white"><div className="container"><div className="sb-section-head"><div><span className="sb-kicker">The problem we solve</span><h2>A cheap room can still be an expensive daily decision.</h2></div></div><div className="row g-4">{[['bi-clock-history','Hidden commute cost','Understand the distance from a property to the place you actually travel to every day.'],['bi-signpost-split','Scattered information','Compare transport, healthcare, supermarkets and food options without opening separate searches.'],['bi-shield-check','Trust uncertainty','Use moderated listings, owner status and safer in-platform conversations to make a more informed choice.']].map(([icon,title,body],i)=><div className="col-lg-4" key={title}><article className="sb-about-card"><span>0{i+1}</span><i className={`bi ${icon}`}/><h3>{title}</h3><p>{body}</p></article></div>)}</div></div></section>
    <section className="sb-section sb-about-process"><div className="container"><div className="row g-5"><div className="col-lg-5"><span className="sb-kicker">How it works</span><h2>Helpful intelligence, with clear boundaries.</h2><p>Property eligibility, budget, facilities and privacy are enforced by the platform. Semantic relevance and straight-line distance then help you compare suitable options.</p></div><div className="col-lg-7"><ol>{process.map(([title,body])=><li key={title}><span><i className="bi bi-check2"/></span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol></div></div></div></section>
    <section className="sb-section bg-white"><div className="container"><div className="sb-transparency"><div><span className="sb-kicker">Built around trust</span><h2>Useful technology should be honest about its limits.</h2></div><div className="row g-3"><div className="col-md-6"><p><i className="bi bi-check-circle-fill"/> Keeps exact addresses and private messages outside matching.</p><p><i className="bi bi-check-circle-fill"/> Shows published, available properties only.</p><p><i className="bi bi-check-circle-fill"/> Keeps search available if the AI service is temporarily offline.</p></div><div className="col-md-6"><p><i className="bi bi-x-circle-fill"/> Does not calculate live traffic or guarantee travel time.</p><p><i className="bi bi-x-circle-fill"/> Does not verify a property solely through AI.</p><p><i className="bi bi-x-circle-fill"/> Does not process rent or deposit payments.</p></div></div></div></div></section>
  </PublicLayout>;
}
