import {useQuery} from '@tanstack/react-query';
import {Link,useParams} from 'react-router-dom';
import {api} from '../api';
import {RoleLayout} from '../components/Shell';

type OwnerReview={id:number;rating:number;body:string;moderation_status:string;tenant:{name:string};listing:{id:number;title:string}};
export function OwnerReviews(){const{data}=useQuery({queryKey:['owner-reviews'],queryFn:async()=>(await api.get('/owner/reviews')).data.data});const items:OwnerReview[]=data?.data||[];return <RoleLayout role="owner"><div className="dash-head"><div><span className="eyebrow">Resident feedback</span><h1>Reviews & AI monitoring</h1><p>Read-only owner view. Moderation remains independent.</p></div></div><div className="panel">{items.map(r=><article className="review" key={r.id}><div className="review-head"><div><strong>{r.tenant.name}</strong> on <Link className="text-link" to={`/listing/${r.listing.id}`}>{r.listing.title}</Link></div><span className="stars">{'★'.repeat(r.rating)}</span></div><p>{r.body}</p><span className={`status status-${r.moderation_status}`}>{r.moderation_status}</span></article>)}{!items.length&&<div className="empty"><h3>No reviews received yet</h3></div>}</div></RoleLayout>}

type History={id:number;previous_status:string;new_status:string;reason?:string;created_at:string;actor?:{name:string;role:string}};
export function ListingHistory(){const{id}=useParams();const{data=[]}=useQuery({queryKey:['owner-listing-history',id],queryFn:async()=>(await api.get(`/owner/listings/${id}/history`)).data.data as History[]});return <RoleLayout role="owner"><div className="dash-head"><div><span className="eyebrow">Moderation trail</span><h1>Listing status history</h1></div><Link className="btn btn-ghost" to="/owner/listings">Back to listings</Link></div><div className="panel timeline">{data.map(row=><div className="list-row" key={row.id}><span className="notif-icon">{row.new_status==='published'?'✓':'•'}</span><div className="list-copy"><strong>{row.previous_status||'created'} → {row.new_status}</strong><span>{row.reason||'No note'} • {row.actor?.name} ({row.actor?.role}) • {new Date(row.created_at).toLocaleString('en-LK',{timeZone:'Asia/Colombo'})}</span></div></div>)}{!data.length&&<div className="empty"><p>No status changes recorded.</p></div>}</div></RoleLayout>}
