import {FormEvent,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {api,csrf} from '../api';
import {Header} from '../components/Shell';

function Page({title,children}:{title:string;children:React.ReactNode}){return <><Header/><main id="main" className="auth-page"><div className="auth-art"><div className="auth-quote"><span className="eyebrow">Account recovery</span><h2>Your Buddy helps you get safely back home.</h2></div></div><section className="auth-panel"><div className="auth-box"><span className="eyebrow">BodimBuddy.lk</span><h1>{title}</h1>{children}</div></section></main></>}
const errorMessage=(error:unknown)=>(error as {message?:string})?.message||'Something went wrong. Please try again.';

export function ForgotPassword(){const[message,setMessage]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');setBusy(true);try{await csrf();await api.post('/auth/forgot-password',{email:new FormData(e.currentTarget).get('email')});setMessage('If that account exists, a password reset link has been sent.')}catch(reason){setError(errorMessage(reason))}finally{setBusy(false)}};return <Page title="Reset your password"><p>Enter your account email and we’ll send the secure next step.</p>{error&&<div className="form-error show" role="alert">{error}</div>}{message?<div className="notice notice-info" role="status">{message}</div>:<form className="form" onSubmit={submit}><label className="field">Email address<input className="input" name="email" type="email" autoComplete="email" required/></label><button className="btn btn-primary" disabled={busy}>{busy?'Sending…':'Send recovery link'}</button></form>}<div className="auth-switch"><Link className="text-link" to="/login">Back to login</Link></div></Page>}

export function ResetPassword(){const[params]=useSearchParams();const[message,setMessage]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const token=params.get('token');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');const f=new FormData(e.currentTarget);if(f.get('password')!==f.get('password_confirmation')){setError('The password confirmation does not match.');return}setBusy(true);try{await csrf();await api.post('/auth/reset-password',{token,email:f.get('email'),password:f.get('password'),password_confirmation:f.get('password_confirmation')});setMessage('Password reset. You can now log in.')}catch(reason){setError(errorMessage(reason))}finally{setBusy(false)}};return <Page title="Choose a new password">{!token?<div className="notice notice-warning" role="alert">This reset link is incomplete or expired. <Link to="/forgot-password">Request a new link</Link>.</div>:message?<div className="notice notice-info" role="status">{message} <Link to="/login">Log in</Link></div>:<form className="form" onSubmit={submit}>{error&&<div className="form-error show" role="alert">{error}</div>}<label className="field">Email<input className="input" name="email" type="email" autoComplete="email" required defaultValue={params.get('email')||''}/></label><label className="field">New password<input className="input" name="password" type="password" autoComplete="new-password" minLength={8} pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{8,}" title="Use at least 8 characters with uppercase, lowercase and a number." required/><span className="field-help">At least 8 characters with uppercase, lowercase and a number.</span></label><label className="field">Confirm password<input className="input" name="password_confirmation" type="password" autoComplete="new-password" minLength={8} required/></label><button className="btn btn-primary" disabled={busy}>{busy?'Resetting…':'Reset password'}</button></form>}</Page>}
