import {FormEvent,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {api,csrf} from '../api';
import {Header} from '../components/Shell';

function Page({title,children}:{title:string;children:React.ReactNode}){return <><Header/><main className="auth-page"><div className="auth-art"><div className="auth-quote"><span className="eyebrow">Account recovery</span><h2>Secure access without support delays.</h2></div></div><section className="auth-panel"><div className="auth-box"><span className="eyebrow">Smart Bodim</span><h1>{title}</h1>{children}</div></section></main></>}

export function ForgotPassword(){const[message,setMessage]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();await csrf();await api.post('/auth/forgot-password',{email:new FormData(e.currentTarget).get('email')});setMessage('If the account exists, a reset link has been written to the configured mail log.')};return <Page title="Reset your password"><p>Enter your account email. Local development writes the recovery message to the Laravel log.</p>{message?<div className="notice notice-info">{message}</div>:<form className="form" onSubmit={submit}><label className="field">Email address<input className="input" name="email" type="email" required/></label><button className="btn btn-primary">Send recovery link</button></form>}<div className="auth-switch"><Link className="text-link" to="/login">Back to login</Link></div></Page>}

export function ResetPassword(){const[params]=useSearchParams();const[message,setMessage]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await csrf();await api.post('/auth/reset-password',{token:params.get('token'),email:f.get('email'),password:f.get('password'),password_confirmation:f.get('password_confirmation')});setMessage('Password reset. You can now log in.')};return <Page title="Choose a new password">{message?<div className="notice notice-info">{message} <Link to="/login">Log in</Link></div>:<form className="form" onSubmit={submit}><label className="field">Email<input className="input" name="email" type="email" required defaultValue={params.get('email')||''}/></label><label className="field">New password<input className="input" name="password" type="password" minLength={8} required/></label><label className="field">Confirm password<input className="input" name="password_confirmation" type="password" minLength={8} required/></label><button className="btn btn-primary">Reset password</button></form>}</Page>}
