import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {FormEvent,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api';
import {useAuth} from '../auth';
import {ListingCard} from '../components/ListingCard';
import {RoleLayout} from '../components/Shell';
import type {Listing} from '../types';

export function TenantDashboard(){
  const{user}=useAuth();
  const{data=[]}=useQuery({queryKey:['featured'],queryFn:async()=>(await api.get('/listings/featured')).data.data as Listing[]});
  const openAi=(message?:string)=>window.dispatchEvent(new CustomEvent('smartbodim:open-assistant',{detail:message?{message}:undefined}));
  const actions=[
    ['/nearby','bi-geo-alt','Near campus or work','Rank stays by real distance'],
    ['/tenant/favorites','bi-heart','Saved places','Review your shortlist'],
    ['/tenant/messages','bi-chat-dots','Messages','Continue owner conversations'],
    ['/search','bi-sliders','Explore listings','Search with detailed filters'],
  ];
  return <RoleLayout role="tenant">
    <section className="client-welcome">
      <div className="client-welcome-copy"><span className="client-kicker"><i className="bi bi-stars"/> Your personal stay Buddy</span><h1>Welcome back, {user?.name.split(' ')[0]}.</h1><p>Tell Buddy AI where you study or work, what you can spend and what you need nearby. It will turn that into a practical shortlist.</p><div className="client-welcome-actions"><button className="btn client-primary" onClick={()=>openAi()}><i className="bi bi-stars"/> Ask Buddy</button><Link className="btn client-secondary" to="/nearby"><i className="bi bi-signpost-split"/> Find by destination</Link></div>
      </div>
      <aside className="client-prompt"><div className="client-prompt-icon"><i className="bi bi-chat-quote"/></div><span>Try a natural request</span><strong>Find a WiFi room within 10 km of University of Moratuwa under Rs. 35,000.</strong><button onClick={()=>openAi('Find a WiFi room within 10 km of University of Moratuwa under Rs. 35,000')}>Use this request <i className="bi bi-arrow-right"/></button></aside>
    </section>
    <nav className="client-action-grid" aria-label="Tenant quick actions">{actions.map(([to,icon,title,description])=><Link to={to} key={to}><span><i className={`bi ${icon}`}/></span><div><strong>{title}</strong><small>{description}</small></div><i className="bi bi-arrow-up-right"/></Link>)}</nav>
    <section className="client-content-card"><header className="client-section-head"><div><span className="client-kicker">Selected for you</span><h2>Trusted places worth exploring</h2><p>Recently published stays with clear pricing and owner details.</p></div><Link to="/search">View all listings <i className="bi bi-arrow-right"/></Link></header>{data.length?<div className="cards">{data.slice(0,3).map(x=><ListingCard key={x.id} item={x}/>)}</div>:<div className="empty"><h3>No recommendations yet</h3><p>Use the smart finder to build your first shortlist.</p></div>}</section>
  </RoleLayout>
}

export function Favorites(){const qc=useQueryClient();const{data=[]}=useQuery({queryKey:['favorites'],queryFn:async()=>(await api.get('/favorites')).data.data as Listing[]});const remove=useMutation({mutationFn:(id:number)=>api.delete(`/favorites/${id}`),onSuccess:()=>qc.invalidateQueries({queryKey:['favorites']})});return <RoleLayout role="tenant"><div className="dash-head"><div><span className="eyebrow">Your shortlist</span><h1>Saved places</h1></div>{data.length>1&&<Link className="btn btn-primary" to="/tenant/compare">Compare saved places</Link>}</div>{data.length?<div className="cards">{data.map(x=><ListingCard key={x.id} item={x} favorite onFavorite={id=>remove.mutate(id)}/>)}</div>:<div className="empty"><h3>No saved places yet</h3><p>Browse listings and select the heart icon to build a shortlist.</p></div>}</RoleLayout>}

type Saved={id:number;name:string;natural_query:string;filters:Record<string,unknown>;notifications_enabled:boolean};
export function SavedSearches(){const qc=useQueryClient();const[open,setOpen]=useState(false);const{data=[]}=useQuery({queryKey:['saved-searches'],queryFn:async()=>(await api.get('/saved-searches')).data.data as Saved[]});const create=useMutation({mutationFn:(body:unknown)=>api.post('/saved-searches',body),onSuccess:()=>{setOpen(false);void qc.invalidateQueries({queryKey:['saved-searches']})}});const remove=useMutation({mutationFn:(id:number)=>api.delete(`/saved-searches/${id}`),onSuccess:()=>qc.invalidateQueries({queryKey:['saved-searches']})});const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);create.mutate({name:f.get('name'),query:f.get('query'),filters:{city:f.get('city'),maxPrice:Number(f.get('maxPrice')||0)||null},notificationsEnabled:true})};return <RoleLayout role="tenant"><div className="dash-head"><div><span className="eyebrow">Matching alerts</span><h1>Saved searches</h1></div><button className="btn btn-primary" onClick={()=>setOpen(true)}>New saved search</button></div><div className="panel">{data.map(x=><div className="list-row" key={x.id}><div className="notif-icon">⌕</div><div className="list-copy"><strong>{x.name}</strong><span>{x.natural_query||Object.entries(x.filters).filter(([,v])=>v).map(([k,v])=>`${k}: ${v}`).join(' • ')}</span></div><span className="status status-visible">{x.notifications_enabled?'alerts on':'alerts off'}</span><button className="btn btn-danger btn-sm" onClick={()=>remove.mutate(x.id)}>Delete</button></div>)}{!data.length&&<div className="empty"><p>No saved searches yet.</p></div>}</div>{open&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><form className="modal" onSubmit={submit}><h2>Save a property search</h2><div className="form"><label className="field">Name<input className="input" name="name" required maxLength={120}/></label><label className="field">Natural-language query<input className="input" name="query" maxLength={500}/></label><div className="form-row"><label className="field">City<input className="input" name="city"/></label><label className="field">Maximum LKR<input className="input" name="maxPrice" type="number" min="0"/></label></div></div><div className="modal-actions"><button type="button" className="btn btn-ghost" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary">Save and enable alerts</button></div></form></div>}</RoleLayout>}

export function Compare(){const{data=[]}=useQuery({queryKey:['favorites'],queryFn:async()=>(await api.get('/favorites')).data.data as Listing[]});const items=data.slice(0,4);const rows:Array<[string,(x:Listing)=>string]>=[['Monthly price',x=>`Rs. ${x.price.toLocaleString('en-LK')}`],['Location',x=>`${x.area}, ${x.city}`],['Type',x=>x.propertyType.replaceAll('_',' ')],['Gender rule',x=>x.genderRule.replaceAll('_',' ')],['Occupancy',x=>String(x.occupancy)],['Facilities',x=>x.facilities.join(', ')||'—'],['Rating',x=>`${x.rating} / 5`],['Available',x=>x.available?'Yes':'No']];return <RoleLayout role="tenant"><div className="dash-head"><div><span className="eyebrow">Side-by-side</span><h1>Compare saved places</h1><p>Up to four of your persisted favorites.</p></div></div>{items.length<2?<div className="empty"><h3>Save at least two listings to compare</h3></div>:<div className="table-wrap"><table className="table compare-table"><thead><tr><th>Attribute</th>{items.map(x=><th key={x.id}><Link to={`/listing/${x.id}`}>{x.title}</Link></th>)}</tr></thead><tbody>{rows.map(([label,read])=><tr key={label}><th>{label}</th>{items.map(x=><td key={x.id}>{read(x)}</td>)}</tr>)}</tbody></table></div>}</RoleLayout>}

type MyReview={id:number;rating:number;body:string;moderation_status:string;listing:{id:number;title:string}};
export function MyReviews(){const qc=useQueryClient();const{data=[]}=useQuery({queryKey:['my-reviews'],queryFn:async()=>(await api.get('/my-reviews')).data.data as MyReview[]});const remove=useMutation({mutationFn:(id:number)=>api.delete(`/reviews/${id}`),onSuccess:()=>qc.invalidateQueries({queryKey:['my-reviews']})});return <RoleLayout role="tenant"><div className="dash-head"><div><span className="eyebrow">Your opinions</span><h1>My reviews</h1></div></div><div className="panel">{data.map(r=><article className="review" key={r.id}><div className="review-head"><Link to={`/listing/${r.listing.id}`}><strong>{r.listing.title}</strong></Link><span className="stars">{'★'.repeat(r.rating)}</span></div><p>{r.body}</p><div className="table-actions"><span className={`status status-${r.moderation_status}`}>{r.moderation_status}</span><button className="btn btn-danger btn-sm" onClick={()=>remove.mutate(r.id)}>Delete</button></div></article>)}{!data.length&&<div className="empty"><p>You have not reviewed a property.</p></div>}</div></RoleLayout>}
